REST API updates (#532)
* Fixed indenting

* Added new files

* Now tracking experiment progress

* Experiment Status updates

* Added a method to AnalysisGraph to freeze an edge.

* Created a static Model class to go with existing Experiment class

* Base status now returns only 'status' query result column

* base status is now a public method

* Added some debug output

* Test Experiment time steps increased for progress monitoring

* Deleted early TrainingStatus class

* Added a test script to create a model and follow its training

* Added a test script to create a model and follow its training

* model-create now checks for a valid input file

* renamed the flag that toggles debug output to avoid a collison with 'DEBUG'

* model-create will now advise the user if an untrained model exists

* Model ID added to ModelCreationResponse JSON

* get_delphi_url set to localhost

* Model ID returned in JSON if not found in database

* Cleanup of REST API before edit-edges development

* Updated AnalysisGraph.hpp with latest edit-weights definition

Co-authored-by: Manujinda Wathugala <manujinda@email.arizona.edu>

diff --git a/tests/wm/scripts/causemos_api_3.0.0/model-create b/tests/wm/scripts/causemos_api_3.0.0/model-create
--- a/tests/wm/scripts/causemos_api_3.0.0/model-create
+++ b/tests/wm/scripts/causemos_api_3.0.0/model-create
@@ -18,30 +18,39 @@ if [[ $inputFile == "" ]]; then
 
     echo "Please specify a filename."
     echo "Usage: $0 filename"
-
-else
-    # make sure file has an "id" JSON field
-    id=$('jq' -r '.id' < $inputFile)
-
-    if [[ $id == "null" ]]; then
-        echo "please specify an input file with a valid 'id' field"
-    else
-        echo "Creating model id: $id"
-        login="-u me:ivilab4fun"
-        url=$(./get_delphi_url)
-        endpoint="/create-model"
-
-        call="curl -s $login -X POST $url$endpoint -d @$inputFile"
-        echo "Call:"
-        echo $call
-
-        call_time=$(date +%T.%3N)
-        response=$($call)
-        response_time=$(date +%T.%3N)
-
-        echo "Response:"
-        echo $response | jq
-        echo "Server queried: $call_time"
-        echo "Server replied: $response_time"
-    fi
+    exit 1
 fi
+
+# make sure the input is a regular file and it exists
+if test -f "$inputFile"; then
+    echo "Reading input file $inputFile"
+else
+    echo "Could not read input file $inputFile"
+    exit 1
+fi
+
+# make sure file has an "id" JSON field
+id=$('jq' -r '.id' < $inputFile)
+
+if [[ $id == "null" ]]; then
+    echo "please specify an input file with a valid 'id' field"
+    exit 1
+fi
+
+echo "Creating model id: $id"
+login="-u me:ivilab4fun"
+url=$(./get_delphi_url)
+endpoint="/create-model"
+
+call="curl -s $login -X POST $url$endpoint -d @$inputFile"
+echo "Call:"
+echo $call
+
+call_time=$(date +%T.%3N)
+response=$($call)
+response_time=$(date +%T.%3N)
+
+echo "Response:"
+echo $response | jq
+echo "Server queried: $call_time"
+echo "Server replied: $response_time"
